name: Deploy complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tomersf/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tomersf/react-test npm test
 
      - run: docker build -t tomersf/complex-client ./client
      - run: docker build -t tomersf/complex-nginx ./nginx
      - run: docker build -t tomersf/complex-server ./server
      - run: docker build -t tomersf/complex-worker ./worker
 
      - run: docker push tomersf/complex-client
      - run: docker push tomersf/complex-nginx
      - run: docker push tomersf/complex-server
      - run: docker push tomersf/complex-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex
          environment_name: Complex-env
          existing_bucket_name: elasticbeanstalk-us-east-1-995673743848
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip